# Generated by Django 4.0.2 on 2022-03-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_category_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount_left', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_bought', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='shop.product')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'db_table': 'shop_sales',
                'ordering': ['-paid_at'],
            },
        ),
    ]
