# Generated by Django 4.0.2 on 2022-03-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_amount_left_sales_amount_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='shop.product'),
        ),
    ]
