# Generated by Django 4.0.2 on 2022-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_sales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_bought',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
